-- MySQL Script generated by MySQL Workbench
-- Thu Mar 13 12:06:03 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema money_mind_db
-- -----------------------------------------------------

-- Crear la base de datos money_mind_db si no existe
CREATE SCHEMA IF NOT EXISTS `money_mind_db` DEFAULT CHARACTER SET utf8 ;
USE `money_mind_db` ;

-- -----------------------------------------------------
-- Table `money_mind_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id_users` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `register_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_users`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `money_mind_db`.`spends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spends` (
  `id_spends` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NOT NULL,
  `amount` INT NOT NULL,
  `spend_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fk_users_id_users` INT NOT NULL,
  PRIMARY KEY (`id_spends`),
  INDEX `fk_spends_users_idx` (`fk_users_id_users` ASC) VISIBLE,
  CONSTRAINT `fk_spends_users`
    FOREIGN KEY (`fk_users_id_users`)
    REFERENCES `users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
